# 基础镜像使用java
# 使用 docker exec -it ID /bin/sh
FROM eclipse-temurin:17-jre-alpine
# bin/bash 有 mkdir命令
#FROM eclipse-temurin:17-jre-jammy

#作者
MAINTAINER 阿星

# volume 指定临时文件目录为/tmp, 在主机/var/lib/docker 目录下创建一个临时文件夹并链接到容器的/tmp
#ARG workdir=/app

VOLUME /logs
VOLUME /data
#ENV APP_NAME=server.jar

#设置工作目录，设置了工作目录，它将会作用于该指令后面的 RUN, CMD, ENTRYPOINT, COPY , ADD 指令
#WORKDIR /app

#RUN bash -c 'mkdir -p {config,target}'
RUN sh -c 'mkdir config target'

#将配置文件添加到容器中
COPY /docker/application.yml /config/application.yml

#将本地文件添加到容器中
COPY /target/*.jar /target/server.jar

#配置容器，使其可执行化
# 自动识别config/application.yml

# 指定环境
ENTRYPOINT java -jar -Dspring.profiles.active=prd /target/server.jar

# 不指定,用application.yml 控制
ENTRYPOINT java -jar  /target/server.jar

#配置时区，不然会发现打包到docker中启动的容器日志里的时间是差8个小时的
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

# 暴露端口,需要和服务的端口一致
EXPOSE 12033

# 命令运行
# restart=always; privileged=true; network=demo-network
# idea配置项
# --restart=always --privileged=true --network=demo-network
