// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simple.proto

package com.github.axinger.api;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 value = 2;</code>
   * @return The value.
   */
  int getValue();
}
