// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simple.proto

package com.github.axinger.api;

public interface MyStructDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyStructDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Struct details = 1;</code>
   * @return Whether the details field is set.
   */
  boolean hasDetails();
  /**
   * <code>.google.protobuf.Struct details = 1;</code>
   * @return The details.
   */
  com.google.protobuf.Struct getDetails();
  /**
   * <code>.google.protobuf.Struct details = 1;</code>
   */
  com.google.protobuf.StructOrBuilder getDetailsOrBuilder();
}
