// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response_payload.proto

package com.github.axinger.api;

public final class ResponsePayloadOuterClass {
  private ResponsePayloadOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponsePayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.axinger.api.ResponsePayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     * @return Whether the empty field is set.
     */
    boolean hasEmpty();
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     * @return The empty.
     */
    com.google.protobuf.Empty getEmpty();
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     */
    com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder();

    /**
     * <code>.com.github.axinger.api.User user = 2;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>.com.github.axinger.api.User user = 2;</code>
     * @return The user.
     */
    UserOuterClass.User getUser();
    /**
     * <code>.com.github.axinger.api.User user = 2;</code>
     */
    UserOuterClass.UserOrBuilder getUserOrBuilder();

    /**
     * <code>.com.github.axinger.api.Product product = 3;</code>
     * @return Whether the product field is set.
     */
    boolean hasProduct();
    /**
     * <code>.com.github.axinger.api.Product product = 3;</code>
     * @return The product.
     */
    ProductOuterClass.Product getProduct();
    /**
     * <code>.com.github.axinger.api.Product product = 3;</code>
     */
    ProductOuterClass.ProductOrBuilder getProductOrBuilder();

    /**
     * <code>.com.github.axinger.api.UserList userList = 4;</code>
     * @return Whether the userList field is set.
     */
    boolean hasUserList();
    /**
     * <code>.com.github.axinger.api.UserList userList = 4;</code>
     * @return The userList.
     */
    UserOuterClass.UserList getUserList();
    /**
     * <code>.com.github.axinger.api.UserList userList = 4;</code>
     */
    UserOuterClass.UserListOrBuilder getUserListOrBuilder();

    public ResponsePayload.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code com.github.axinger.api.ResponsePayload}
   */
  public static final class ResponsePayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.axinger.api.ResponsePayload)
      ResponsePayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponsePayload.newBuilder() to construct.
    private ResponsePayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponsePayload() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponsePayload();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResponsePayloadOuterClass.internal_static_com_github_axinger_api_ResponsePayload_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResponsePayloadOuterClass.internal_static_com_github_axinger_api_ResponsePayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponsePayload.class, Builder.class);
    }

    private int payloadCase_ = 0;
    private Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      EMPTY(1),
      USER(2),
      PRODUCT(3),
      USERLIST(4),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 1: return EMPTY;
          case 2: return USER;
          case 3: return PRODUCT;
          case 4: return USERLIST;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int EMPTY_FIELD_NUMBER = 1;
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     * @return Whether the empty field is set.
     */
    @Override
    public boolean hasEmpty() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     * @return The empty.
     */
    @Override
    public com.google.protobuf.Empty getEmpty() {
      if (payloadCase_ == 1) {
         return (com.google.protobuf.Empty) payload_;
      }
      return com.google.protobuf.Empty.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     */
    @Override
    public com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder() {
      if (payloadCase_ == 1) {
         return (com.google.protobuf.Empty) payload_;
      }
      return com.google.protobuf.Empty.getDefaultInstance();
    }

    public static final int USER_FIELD_NUMBER = 2;
    /**
     * <code>.com.github.axinger.api.User user = 2;</code>
     * @return Whether the user field is set.
     */
    @Override
    public boolean hasUser() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.com.github.axinger.api.User user = 2;</code>
     * @return The user.
     */
    @Override
    public UserOuterClass.User getUser() {
      if (payloadCase_ == 2) {
         return (UserOuterClass.User) payload_;
      }
      return UserOuterClass.User.getDefaultInstance();
    }
    /**
     * <code>.com.github.axinger.api.User user = 2;</code>
     */
    @Override
    public UserOuterClass.UserOrBuilder getUserOrBuilder() {
      if (payloadCase_ == 2) {
         return (UserOuterClass.User) payload_;
      }
      return UserOuterClass.User.getDefaultInstance();
    }

    public static final int PRODUCT_FIELD_NUMBER = 3;
    /**
     * <code>.com.github.axinger.api.Product product = 3;</code>
     * @return Whether the product field is set.
     */
    @Override
    public boolean hasProduct() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.com.github.axinger.api.Product product = 3;</code>
     * @return The product.
     */
    @Override
    public ProductOuterClass.Product getProduct() {
      if (payloadCase_ == 3) {
         return (ProductOuterClass.Product) payload_;
      }
      return ProductOuterClass.Product.getDefaultInstance();
    }
    /**
     * <code>.com.github.axinger.api.Product product = 3;</code>
     */
    @Override
    public ProductOuterClass.ProductOrBuilder getProductOrBuilder() {
      if (payloadCase_ == 3) {
         return (ProductOuterClass.Product) payload_;
      }
      return ProductOuterClass.Product.getDefaultInstance();
    }

    public static final int USERLIST_FIELD_NUMBER = 4;
    /**
     * <code>.com.github.axinger.api.UserList userList = 4;</code>
     * @return Whether the userList field is set.
     */
    @Override
    public boolean hasUserList() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.com.github.axinger.api.UserList userList = 4;</code>
     * @return The userList.
     */
    @Override
    public UserOuterClass.UserList getUserList() {
      if (payloadCase_ == 4) {
         return (UserOuterClass.UserList) payload_;
      }
      return UserOuterClass.UserList.getDefaultInstance();
    }
    /**
     * <code>.com.github.axinger.api.UserList userList = 4;</code>
     */
    @Override
    public UserOuterClass.UserListOrBuilder getUserListOrBuilder() {
      if (payloadCase_ == 4) {
         return (UserOuterClass.UserList) payload_;
      }
      return UserOuterClass.UserList.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payloadCase_ == 1) {
        output.writeMessage(1, (com.google.protobuf.Empty) payload_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (UserOuterClass.User) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (ProductOuterClass.Product) payload_);
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (UserOuterClass.UserList) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payloadCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.google.protobuf.Empty) payload_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (UserOuterClass.User) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (ProductOuterClass.Product) payload_);
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (UserOuterClass.UserList) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResponsePayload)) {
        return super.equals(obj);
      }
      ResponsePayload other = (ResponsePayload) obj;

      if (!getPayloadCase().equals(other.getPayloadCase())) return false;
      switch (payloadCase_) {
        case 1:
          if (!getEmpty()
              .equals(other.getEmpty())) return false;
          break;
        case 2:
          if (!getUser()
              .equals(other.getUser())) return false;
          break;
        case 3:
          if (!getProduct()
              .equals(other.getProduct())) return false;
          break;
        case 4:
          if (!getUserList()
              .equals(other.getUserList())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (payloadCase_) {
        case 1:
          hash = (37 * hash) + EMPTY_FIELD_NUMBER;
          hash = (53 * hash) + getEmpty().hashCode();
          break;
        case 2:
          hash = (37 * hash) + USER_FIELD_NUMBER;
          hash = (53 * hash) + getUser().hashCode();
          break;
        case 3:
          hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
          hash = (53 * hash) + getProduct().hashCode();
          break;
        case 4:
          hash = (37 * hash) + USERLIST_FIELD_NUMBER;
          hash = (53 * hash) + getUserList().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResponsePayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponsePayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponsePayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponsePayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponsePayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponsePayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponsePayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponsePayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponsePayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResponsePayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponsePayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponsePayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResponsePayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.axinger.api.ResponsePayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.axinger.api.ResponsePayload)
        ResponsePayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResponsePayloadOuterClass.internal_static_com_github_axinger_api_ResponsePayload_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResponsePayloadOuterClass.internal_static_com_github_axinger_api_ResponsePayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponsePayload.class, Builder.class);
      }

      // Construct using com.github.axinger.api.ResponsePayloadOuterClass.ResponsePayload.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        if (emptyBuilder_ != null) {
          emptyBuilder_.clear();
        }
        if (userBuilder_ != null) {
          userBuilder_.clear();
        }
        if (productBuilder_ != null) {
          productBuilder_.clear();
        }
        if (userListBuilder_ != null) {
          userListBuilder_.clear();
        }
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResponsePayloadOuterClass.internal_static_com_github_axinger_api_ResponsePayload_descriptor;
      }

      @Override
      public ResponsePayload getDefaultInstanceForType() {
        return ResponsePayload.getDefaultInstance();
      }

      @Override
      public ResponsePayload build() {
        ResponsePayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ResponsePayload buildPartial() {
        ResponsePayload result = new ResponsePayload(this);
        if (payloadCase_ == 1) {
          if (emptyBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = emptyBuilder_.build();
          }
        }
        if (payloadCase_ == 2) {
          if (userBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = userBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (productBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = productBuilder_.build();
          }
        }
        if (payloadCase_ == 4) {
          if (userListBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = userListBuilder_.build();
          }
        }
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponsePayload) {
          return mergeFrom((ResponsePayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponsePayload other) {
        if (other == ResponsePayload.getDefaultInstance()) return this;
        switch (other.getPayloadCase()) {
          case EMPTY: {
            mergeEmpty(other.getEmpty());
            break;
          }
          case USER: {
            mergeUser(other.getUser());
            break;
          }
          case PRODUCT: {
            mergeProduct(other.getProduct());
            break;
          }
          case USERLIST: {
            mergeUserList(other.getUserList());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getEmptyFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getUserFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getProductFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 3;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getUserListFieldBuilder().getBuilder(),
                    extensionRegistry);
                payloadCase_ = 4;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int payloadCase_ = 0;
      private Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> emptyBuilder_;
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       * @return Whether the empty field is set.
       */
      @Override
      public boolean hasEmpty() {
        return payloadCase_ == 1;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       * @return The empty.
       */
      @Override
      public com.google.protobuf.Empty getEmpty() {
        if (emptyBuilder_ == null) {
          if (payloadCase_ == 1) {
            return (com.google.protobuf.Empty) payload_;
          }
          return com.google.protobuf.Empty.getDefaultInstance();
        } else {
          if (payloadCase_ == 1) {
            return emptyBuilder_.getMessage();
          }
          return com.google.protobuf.Empty.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public Builder setEmpty(com.google.protobuf.Empty value) {
        if (emptyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          emptyBuilder_.setMessage(value);
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public Builder setEmpty(
          com.google.protobuf.Empty.Builder builderForValue) {
        if (emptyBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          emptyBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public Builder mergeEmpty(com.google.protobuf.Empty value) {
        if (emptyBuilder_ == null) {
          if (payloadCase_ == 1 &&
              payload_ != com.google.protobuf.Empty.getDefaultInstance()) {
            payload_ = com.google.protobuf.Empty.newBuilder((com.google.protobuf.Empty) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 1) {
            emptyBuilder_.mergeFrom(value);
          } else {
            emptyBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 1;
        return this;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public Builder clearEmpty() {
        if (emptyBuilder_ == null) {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 1) {
            payloadCase_ = 0;
            payload_ = null;
          }
          emptyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public com.google.protobuf.Empty.Builder getEmptyBuilder() {
        return getEmptyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      @Override
      public com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder() {
        if ((payloadCase_ == 1) && (emptyBuilder_ != null)) {
          return emptyBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 1) {
            return (com.google.protobuf.Empty) payload_;
          }
          return com.google.protobuf.Empty.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder>
          getEmptyFieldBuilder() {
        if (emptyBuilder_ == null) {
          if (!(payloadCase_ == 1)) {
            payload_ = com.google.protobuf.Empty.getDefaultInstance();
          }
          emptyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder>(
                  (com.google.protobuf.Empty) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 1;
        onChanged();;
        return emptyBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          UserOuterClass.User, UserOuterClass.User.Builder, UserOuterClass.UserOrBuilder> userBuilder_;
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       * @return Whether the user field is set.
       */
      @Override
      public boolean hasUser() {
        return payloadCase_ == 2;
      }
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       * @return The user.
       */
      @Override
      public UserOuterClass.User getUser() {
        if (userBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (UserOuterClass.User) payload_;
          }
          return UserOuterClass.User.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return userBuilder_.getMessage();
          }
          return UserOuterClass.User.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       */
      public Builder setUser(UserOuterClass.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       */
      public Builder setUser(
          UserOuterClass.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       */
      public Builder mergeUser(UserOuterClass.User value) {
        if (userBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != UserOuterClass.User.getDefaultInstance()) {
            payload_ = UserOuterClass.User.newBuilder((UserOuterClass.User) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            userBuilder_.mergeFrom(value);
          } else {
            userBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          userBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       */
      public UserOuterClass.User.Builder getUserBuilder() {
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       */
      @Override
      public UserOuterClass.UserOrBuilder getUserOrBuilder() {
        if ((payloadCase_ == 2) && (userBuilder_ != null)) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (UserOuterClass.User) payload_;
          }
          return UserOuterClass.User.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.axinger.api.User user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          UserOuterClass.User, UserOuterClass.User.Builder, UserOuterClass.UserOrBuilder>
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = UserOuterClass.User.getDefaultInstance();
          }
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              UserOuterClass.User, UserOuterClass.User.Builder, UserOuterClass.UserOrBuilder>(
                  (UserOuterClass.User) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();;
        return userBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ProductOuterClass.Product, ProductOuterClass.Product.Builder, ProductOuterClass.ProductOrBuilder> productBuilder_;
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       * @return Whether the product field is set.
       */
      @Override
      public boolean hasProduct() {
        return payloadCase_ == 3;
      }
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       * @return The product.
       */
      @Override
      public ProductOuterClass.Product getProduct() {
        if (productBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (ProductOuterClass.Product) payload_;
          }
          return ProductOuterClass.Product.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return productBuilder_.getMessage();
          }
          return ProductOuterClass.Product.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       */
      public Builder setProduct(ProductOuterClass.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          productBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       */
      public Builder setProduct(
          ProductOuterClass.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          productBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       */
      public Builder mergeProduct(ProductOuterClass.Product value) {
        if (productBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != ProductOuterClass.Product.getDefaultInstance()) {
            payload_ = ProductOuterClass.Product.newBuilder((ProductOuterClass.Product) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            productBuilder_.mergeFrom(value);
          } else {
            productBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       */
      public Builder clearProduct() {
        if (productBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          productBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       */
      public ProductOuterClass.Product.Builder getProductBuilder() {
        return getProductFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       */
      @Override
      public ProductOuterClass.ProductOrBuilder getProductOrBuilder() {
        if ((payloadCase_ == 3) && (productBuilder_ != null)) {
          return productBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (ProductOuterClass.Product) payload_;
          }
          return ProductOuterClass.Product.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.axinger.api.Product product = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProductOuterClass.Product, ProductOuterClass.Product.Builder, ProductOuterClass.ProductOrBuilder>
          getProductFieldBuilder() {
        if (productBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = ProductOuterClass.Product.getDefaultInstance();
          }
          productBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProductOuterClass.Product, ProductOuterClass.Product.Builder, ProductOuterClass.ProductOrBuilder>(
                  (ProductOuterClass.Product) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        onChanged();;
        return productBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          UserOuterClass.UserList, UserOuterClass.UserList.Builder, UserOuterClass.UserListOrBuilder> userListBuilder_;
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       * @return Whether the userList field is set.
       */
      @Override
      public boolean hasUserList() {
        return payloadCase_ == 4;
      }
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       * @return The userList.
       */
      @Override
      public UserOuterClass.UserList getUserList() {
        if (userListBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (UserOuterClass.UserList) payload_;
          }
          return UserOuterClass.UserList.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return userListBuilder_.getMessage();
          }
          return UserOuterClass.UserList.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       */
      public Builder setUserList(UserOuterClass.UserList value) {
        if (userListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          userListBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       */
      public Builder setUserList(
          UserOuterClass.UserList.Builder builderForValue) {
        if (userListBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          userListBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       */
      public Builder mergeUserList(UserOuterClass.UserList value) {
        if (userListBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != UserOuterClass.UserList.getDefaultInstance()) {
            payload_ = UserOuterClass.UserList.newBuilder((UserOuterClass.UserList) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            userListBuilder_.mergeFrom(value);
          } else {
            userListBuilder_.setMessage(value);
          }
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       */
      public Builder clearUserList() {
        if (userListBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          userListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       */
      public UserOuterClass.UserList.Builder getUserListBuilder() {
        return getUserListFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       */
      @Override
      public UserOuterClass.UserListOrBuilder getUserListOrBuilder() {
        if ((payloadCase_ == 4) && (userListBuilder_ != null)) {
          return userListBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (UserOuterClass.UserList) payload_;
          }
          return UserOuterClass.UserList.getDefaultInstance();
        }
      }
      /**
       * <code>.com.github.axinger.api.UserList userList = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          UserOuterClass.UserList, UserOuterClass.UserList.Builder, UserOuterClass.UserListOrBuilder>
          getUserListFieldBuilder() {
        if (userListBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = UserOuterClass.UserList.getDefaultInstance();
          }
          userListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              UserOuterClass.UserList, UserOuterClass.UserList.Builder, UserOuterClass.UserListOrBuilder>(
                  (UserOuterClass.UserList) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        onChanged();;
        return userListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.axinger.api.ResponsePayload)
    }

    // @@protoc_insertion_point(class_scope:com.github.axinger.api.ResponsePayload)
    private static final ResponsePayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResponsePayload();
    }

    public static ResponsePayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponsePayload>
        PARSER = new com.google.protobuf.AbstractParser<ResponsePayload>() {
      @Override
      public ResponsePayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResponsePayload> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponsePayload> getParserForType() {
      return PARSER;
    }

    @Override
    public ResponsePayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_axinger_api_ResponsePayload_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_axinger_api_ResponsePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026response_payload.proto\022\026com.github.axi" +
      "nger.api\032\033google/protobuf/empty.proto\032\nu" +
      "ser.proto\032\rproduct.proto\"\335\001\n\017ResponsePay" +
      "load\022\'\n\005empty\030\001 \001(\0132\026.google.protobuf.Em" +
      "ptyH\000\022,\n\004user\030\002 \001(\0132\034.com.github.axinger" +
      ".api.UserH\000\0222\n\007product\030\003 \001(\0132\037.com.githu" +
      "b.axinger.api.ProductH\000\0224\n\010userList\030\004 \001(" +
      "\0132 .com.github.axinger.api.UserListH\000B\t\n" +
      "\007payloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          UserOuterClass.getDescriptor(),
          ProductOuterClass.getDescriptor(),
        });
    internal_static_com_github_axinger_api_ResponsePayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_axinger_api_ResponsePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_axinger_api_ResponsePayload_descriptor,
        new String[] { "Empty", "User", "Product", "UserList", "Payload", });
    com.google.protobuf.EmptyProto.getDescriptor();
    UserOuterClass.getDescriptor();
    ProductOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
