// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simple.proto

package com.github.axinger.api;

public final class SimpleProto {
  private SimpleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyStructDto_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyStructDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Simple.proto\032\036google/protobuf/wrappers" +
      ".proto\032\034google/protobuf/struct.proto\"(\n\t" +
      "MyRequest\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\005\"-" +
      "\n\nMyResponse\022\017\n\007message\030\001 \001(\t\022\016\n\006result\030" +
      "\002 \001(\003\"7\n\013MyStructDto\022(\n\007details\030\001 \001(\0132\027." +
      "google.protobuf.Struct2\247\001\n\006Simple\022%\n\010One" +
      "ToOne\022\n.MyRequest\032\013.MyResponse\"\000\022B\n\004Get1" +
      "\022\034.google.protobuf.StringValue\032\034.google." +
      "protobuf.StringValue\0222\n\004Get2\022\034.google.pr" +
      "otobuf.StringValue\032\014.MyStructDtoB\'\n\026com." +
      "github.axinger.apiB\013SimpleProtoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyRequest_descriptor,
        new String[] { "Name", "Value", });
    internal_static_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyResponse_descriptor,
        new String[] { "Message", "Result", });
    internal_static_MyStructDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MyStructDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyStructDto_descriptor,
        new String[] { "Details", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
