// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.github.axinger.api;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022user_service.proto\022\026com.github.axinger" +
      ".api\032\021status_code.proto\032\026response_payloa" +
      "d.proto\032\016response.proto\032\nuser.proto2`\n\013U" +
      "serService\022Q\n\013GetUserList\022 .com.github.a" +
      "xinger.api.UserList\032 .com.github.axinger" +
      ".api.Responseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          StatusCodeOuterClass.getDescriptor(),
          ResponsePayloadOuterClass.getDescriptor(),
          ResponseOuterClass.getDescriptor(),
          UserOuterClass.getDescriptor(),
        });
    StatusCodeOuterClass.getDescriptor();
    ResponsePayloadOuterClass.getDescriptor();
    ResponseOuterClass.getDescriptor();
    UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
