package com.ax.db.mapper.db1;


import com.ax.db.entity.db1.Userinfo;

import java.util.List;

/**
 * @author axing
 */
public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    Userinfo selectByPrimaryKey(Long id);

    Userinfo selectUserWithRelo(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userinfo record);

    /**
     * 注册获得是否已经有了
     */
    int getCountByusername(String username);

    /**
     * 按照名username查找
     */
    Userinfo getByusername(String username);

    /**
     * 按照名username和passwor查找
     */
    Userinfo getModelByusernameAndpassword(String username, String password);

    /**
     * 查询所有
     *
     * @return
     */
    List<Userinfo> getAll();





}