spring:
  profiles:
    # 这个用来打包
    #    active: '@my-env@'
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


axinger:
  delayExpression: 2000L
#server:
#  servlet:
#    context-path: /axinger
