server:
  port: 11011
  servlet:
    context-path: /
spring:
  profiles:
    include:
      swagger
  application:
    name: oss-demo

axinger:
  oss:
    endpoint: http://localhost:19000
    access-key-id: admin
    secret-access-key: admin123

