server:
  port: 10252

spring:
  application:
    name: admin-server-demo # 给client应用取个名字
  jackson:
    serialization:
      indent_output: true

logging:
  file:
    path: /logs/${spring.application.name}

endpoints:
  health:
    sensitive: false

