server:
  port: 10202
spring:
  application:
    name: a04-spring-boot-mybatis-plus

  #SpringBoot中会集成flyway的版本
  flyway:
    #开启自动创建flyway元数据表标识 默认: false
    baseline-on-migrate: true
    #如果数据库中已经存在数据，从基线版本之前的脚本不再执行
    enabled: true
  #    log颜色
  output:
    ansi:
      enabled: always

  profiles:
    #    active: sqlserver
    active: mysql
#    active: h2
#    active: pgsql


mybatis-plus:
  #枚举包,必须有 3.5.1 取消了
  #  type-enums-package: com.ax.a16.enums
  #  mapper-locations: classpath*:/mybatis/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.example.demo.model
  #  configuration:
  #开启下划线转驼峰
  #  map-underscore-to-camel-case: true
  #  #开启返回map结果集的下划线转驼峰
  #  object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志, info级别的,也可以直接让 对应的mapper debug级别
    call-setters-on-nulls: true # 返回null值
  #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#logging:
#  level:
#    com.github.axinger.mapper: debug

axinger:
  tenant:
    # 是否开启租户模式
    enable: true
    # 需要排除的多租户的表
    exclusionTable:
      - "t_sys_district"
      - "oauth_client_details"
    # 租户字段名称
    column: tenant_id


