server:
  port: 10707

spring:
  application:
    name: mall-order-app #订单作为消费者
  zipkin:
    base-url: http://hadoop135:9411/
    sender:
      type: web
  sleuth:
    sampler:
      #抽样百分比，默认10%的数据发到zipkin，1为100%
      probability: 1
server-url:
  nacos-payment-service: http://mall-payment-app
  gateway-service: http://mall-gateway-app

  payment-url: http://localhost:10707

server-name:
  payment-service: mall-payment-app

