server:
  port: 10405
  servlet:
    context-path: /

spring:
  application:
    name: a0405-jetcache
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    #    host: 127.0.0.1 # Redis服务器地址
    host: hadoop135 # Redis服务器地址
    password: 123456 # Redis服务器连接密码（默认为空）
    database: 13 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    timeout: 5000 # 连接超时时间（毫秒）\
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0  # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

jetcache:
  statIntervalMinutes: 15 #大于0时，通过@CreateCache和@Cached配置出来的Cache自带监控。JetCache会按指定的时间定期通过logger输出统计信息
  areaInCacheName: false
  local:
    default:
      type: caffeine #other choose：caffeine /linkedhashmap
      keyConvertor: jackson #other choose：fastjson/jackson
      limit: 100
    # 更多Caffeine特定配置
    caffeine:
      initialCapacity: 100
      weakKeys: false
      recordStats: true
  remote:
    default:
      type:  redis.springdata #redis
      keyConvertor: fastjson2 #other choose：fastjson/jackson
      broadcastChannel: projectA
      valueEncoder: FASTJSON2   #other choose：kryo/kryo5/java
      valueDecoder: FASTJSON2   #other choose：kryo/kryo5/java
#      valueEncoder: spring-data-redis   #other choose：kryo/kryo5/java
#      valueDecoder: spring-data-redis   #other choose：kryo/kryo5/java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
