spring:
  application:
    name: a04-spring-boot-mybatis-plus
  datasource:
    url: jdbc:postgresql://hadoop132:5432/ax_test2
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    # 显示sql语句
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # 格式化sql语句
        format_sql: true

logging:
  level:
    org:
      hibernate:
        jdbc:
          bind: trace
    # 基本类型绑定
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 枚举类型绑定
    org.hibernate.metamodel.model.convert.internal.NamedEnumValueConverter: trace
