package com.ax.mall.mapper;

import com.ax.mall.entity.Userinfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @author axing
 */
@Mapper
public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    Userinfo selectByPrimaryKey(Long id);

    Userinfo selectUserWithRelo(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userinfo record);

    /**
     * 注册获得是否已经有了
     */
    int getCountByUserName(String username);

    /**
     * 按照名username查找
     */
    Userinfo getByUserName(String username);

    /**
     * 按照名username和passwor查找
     */
    Userinfo getModelByUserNameAndPassword(String username, String password);

    /**
     * 查询所有
     *
     * @return
     */
    List<Userinfo> getAll();


    /**
     * 按照名username 模糊查询:
     * sql: %name ->mybatis: "%"#{name}""
     */
    Userinfo likePrefixUserName(@Param("name") String username);


    Userinfo likeUserName(@Param("name") String username);

}