server:
  port: 10707
  servlet:
    context-path: /order

spring:
  application:
    name: mall-order-app
#  datasource:
#    dynamic:
#      primary: master
#      strict: false
#      datasource:
#        master:
#          url: jdbc:mysql://hadoop102:3306/ax_test01?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver

  zipkin:
    base-url: http://192.168.101.135:9411/
    sender:
      type: web
  sleuth:
    sampler:
      #抽样百分比，默认10%的数据发到zipkin，1为100%
      probability: 1
server-url:
  nacos-payment-service: http://mall-payment-app
  gateway-service: http://mall-gateway-app
server-name:
  payment-service: mall-payment-app
