server:
  port: 10706
spring:
  application:
    name: mall-gateway-app
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*" # 替代 allowedOrigins
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

      # 启用了自动根据服务名建立路由
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order
          uri: lb://mall-order-app
          predicates:
            - Path=/order/**
        #          filters:
        #            - RewritePath=/order/(?<segment>.*),/$\{segment}
        #          filters:
        #            - StripPrefix=1

        - id: payment
          uri: lb://mall-payment-app
          predicates:
            - Path=/payment/**
#          filters:
#            - RewritePath=/payment/(?<segment>.*),/$\{segment}
#          filters:
#            - StripPrefix=1

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    urls:
#      - name: 订单系统
#        url: /order/v3/api-docs
##        display-name: 订单系统22222 # 就是name
#      - name: 支付系统
#        url: /payment/v3/api-docs


knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 订单服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /order/v3/api-docs
        service-name: mall-order-app
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /order
        order: 3
      - name: 支付服务
        url: /payment/v3/api-docs
        service-name: mall-payment-app
        # 路由前缀
        context-path: /payment
        order: 2
