server:
  port: 10706
spring:
  application:
    name: mall-gateway-app
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*" # 替代 allowedOrigins
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: mall-order-app
          uri: lb://mall-order-app
          predicates:
            - Path=/order/**

        - id: mall-payment-app
          uri: lb://mall-payment-app
          predicates:
            - Path=/payment/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 订单系统
        url: /order/v3/api-docs
      - name: 支付系统
        url: /payment/v3/api-docs
