server:
  servlet:
    context-path: /
  port: 11014

spring:
  application:
    name: redis-demo
  jackson:
    date-format: yyyy年MM月dd日 HH:mm:ss
  datasource:
    url: jdbc:mysql://hadoop102:3306/ax_test1?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 1800000     # 缓存默认有效时长，以毫秒为单位
  redis:
    #    host: 127.0.0.1 # Redis服务器地址
    host: hadoop135 # Redis服务器地址
    password: 123456 # Redis服务器连接密码（默认为空）
    database: 13 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    timeout: 5000 # 连接超时时间（毫秒）\
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0  # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
