# 端口
server:
  port: 10251
#开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有端点（生产环境慎用！）
        # 或按需选择：health, info, metrics, prometheus...
spring:
  application:
    name: a25admin-client-demo # 给client应用取个名字
  boot:
    admin:
      client:
        url: http://localhost:10252   #这里配置admin server 的地址

#logging:
#  config: classpath:logback-spring.xml

#系统日志配置
logging:
  config: classpath:logback-spring.xml
  #spring admin boot日志输出配置,需要跟logback-spring.xml配置中日志路径一致
  file:
    name: logs/a25admin-client-demo/error.log
