server:
  port: 12102
  tomcat:
    max-connections: 10000
    threads:
      max: 600
      min-spare: 50
    connection-timeout: 30000
spring:
  application:
    name: a21-grpc-server

# gRPC有关的配置，这里只需要配置服务端口号默认9090
grpc:
  server:
    port: 19898
