spring:
  application:
    name: a36-logback-prd

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


logging:
  #  config: classpath:logback-spring.xml # 默认加载
  config: classpath:logback-spring-test01.xml # 通用归档
  #  config: classpath:logback-spring-test03.xml # 自定义业务场景
  #  config: classpath:logback-spring-test06.xml
  file:
    path: ./logs/${spring.application.name}
  level:
    org.springframework: info
    org.apache: error
    com.github.axinger: debug
