spring:
  application:
    name: a36-logback

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
#  config: classpath:logback-spring-test00.xml # 默认加载
#  config: classpath:logback-spring-test01.xml # 通用归档
#  config: classpath:logback-spring-test011.xml # 通用归档
#  config: classpath:logback-spring-test03.xml # 自定义业务场景
#  config: classpath:logback-spring-test06.xml
#  file:
#    name: ./logs/${spring.application.name}
  level:
    org.springframework: info
    org.apache: error
    com.github.axinger: debug
    # 不配置 logging.pattern.console 即禁用控制台输出
  pattern:
    console: ''
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有端点（生产环境慎用！）
        # 或按需选择：health, info, metrics, prometheus...
