spring:
  application:
    name: a36-logback

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
#  config: classpath:logback-spring.xml # 默认加载
#  file:
#    path: ./logs/${spring.application.name}
  level:
#    org.springframework.boot.web: error
    org.apache: error
    com.github.axinger: debug
